### ISSUE TITLE
Adding data into database' foreign key returns null

### ISSUE THREAD

**Issue by lim-it-err** [lim-it-ing/MultiUser-Meeting-Scheduler#4]
https://github.com/lim-it-ing/MultiUser-Meeting-Scheduler/blob/0a8177c6b324b2b8ab437abc6a825f839c4ce229/routes/user/make_schedule.js#L25

Hello to all. 
I have implemented INSERT statement on database, including foreign key.
However, as I have put uid(foreign key) returns null.
Any Suggestions?

Thanks.

**Comment by yehsi2000** [comment]
User and Schedule table has NtoM constraint so you can just create each without foreign key and add
`schedule.addUser(user)`
[reference](https://sequelize.org/docs/v6/advanced-association-concepts/advanced-many-to-many/)
